### ISSUE TITLE
Devices not found most of the time - timeout 2 short

### ISSUE THREAD

**Issue by mruiter** [WillooWisp/com.weatherflow.smartweatherstation#1]
Most of the time adding my stations they can't be found.
This is because the devices sometimes dont respond within the current discovery timesout.
Maybee a max timeout thats a bit higher would be better , i guess a lot of users wil start to report that the devices cant be found after 1 or 2 tries.

**Comment by WillooWisp** [comment]
Thanks for reporting this, I guess you are the first user of this app just published today. I had 5 seconds earlier, then increased to 10 seconds, which has worked for me. But, I will look into improving this, but as you say, for now doubling the timeout might be fine.

**Comment by daneedk** [comment]
I'm probably the second user of the app :) for me it worked flawlessly, guess I was lucky.
Thanks for making this app!

**Comment by WillooWisp** [comment]
I have doubled the timeout now, release is pending approval. I actually did not think anyone would be interested in this app, more than me :), since I thought the Smart Weather Station was mainly sold in US and that the Homey was not so common there yet.

I will add support for more sensor readings and flow triggers in the upcoming releases.

**Comment by daneedk** [comment]
There are quite some people outside the US that ordered one from Indigogo and also some interrest from Homey users. 
Maybe its an idea you create a topic on https://community.athom.com so it can be discussed there, you can also add a link to that topic in app.json 
Like this: https://github.com/daneedk/com.uc.heimdall/blob/cab3dd866910c8cc51c5aaf8a66b08ee459ff74f/app.json#L28

You can also link to a paypal.me address like this: https://github.com/daneedk/com.uc.heimdall/blob/cab3dd866910c8cc51c5aaf8a66b08ee459ff74f/app.json#L16-L22
