### ISSUE TITLE
Low read out rain per hour hr/mm

### ISSUE THREAD

**Issue by pjmpessers** [WillooWisp/com.weatherflow.smartweatherstation#8]
When "Updated rain measurements to use four decimals." was introduced with V0.4.0 i see a wrong read out rain per hour. My wfpiconsole has a read out of 2.4 mm/hr, but homey say 0.0395 mm. Can this be fixed?

**Comment by WillooWisp** [comment]
Your wfpiconsole?

Have you verified with the Tempest app, looks correct for me. 

It is not mm/hour, but mm of Rain reported last minute.

**Comment by pjmpessers** [comment]
Sorry. I mean compared to my tempest app and wfpiconsole that i use as my weatherstation display.

https://community.weatherflow.com/t/weatherflow-piconsole/1933

**Comment by WillooWisp** [comment]
But Homey shows you current Rain in mm last minute and total over the day.

/ Joel Fjordén
________________________________

**Comment by pjmpessers** [comment]
Yes it does. Is the rain in minutes? Not in hours

**Comment by pjmpessers** [comment]
![20210121_215920_resized](https://user-images.githubusercontent.com/34476404/105412270-c9e1b800-5c34-11eb-84cb-b7aefb1fcb6a.jpg)
![Screenshot_20210121-215908_WS View](https://user-images.githubusercontent.com/34476404/105412275-ccdca880-5c34-11eb-9fa6-f0bf327c767d.jpg)
![Screenshot_20210121-215937_Homey](https://user-images.githubusercontent.com/34476404/105412288-cfd79900-5c34-11eb-81fc-cf634c9d7513.jpg)

**Comment by WillooWisp** [comment]
Yes rain is last reported rain for the period configured in tempest, normally every minute.

**Comment by pjmpessers** [comment]
Thanks. I understand. Is there a way in the app-code to change it to every hour? So that after my change i can sideload it? Like *60?

**Comment by WillooWisp** [comment]
Wha's the use case why you need to see the rain per hour?

**Comment by pjmpessers** [comment]
Because the app does it and my wfpiconsole. So that way it's easier to compare.
